using System;

namespace EduTrack.Models
{
    public class Student
    {
        public int Id { get; set; }   // auto-generated by DB
        public string Name { get; set; }
        public string FatherName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string DegreeProgram { get; set; }
        public string Address { get; set; }
    }
}
